// Code generated by musgen-go. DO NOT EDIT.

package exmpls

import (
	dts "github.com/mus-format/mus-stream-dts-go"
	muss "github.com/mus-format/mus-stream-go"
	"github.com/mus-format/mus-stream-go/ord"
)

func MarshalSayHelloCmdMUS(v SayHelloCmd, w muss.Writer) (n int, err error) {
	return ord.MarshalString(v.str, nil, w)
}

func UnmarshalSayHelloCmdMUS(r muss.Reader) (v SayHelloCmd, n int, err error) {
	v.str, n, err = ord.UnmarshalString(nil, r)
	return
}

func SizeSayHelloCmdMUS(v SayHelloCmd) (size int) {
	return ord.SizeString(v.str, nil)
}

func SkipSayHelloCmdMUS(r muss.Reader) (n int, err error) {
	return ord.SkipString(nil, r)
}

var SayHelloCmdDTS = dts.New[SayHelloCmd](SayHelloCmdDTM,
	muss.MarshallerFn[SayHelloCmd](MarshalSayHelloCmdMUS),
	muss.UnmarshallerFn[SayHelloCmd](UnmarshalSayHelloCmdMUS),
	muss.SizerFn[SayHelloCmd](SizeSayHelloCmdMUS),
	muss.SkipperFn(SkipSayHelloCmdMUS))

func MarshalSayFancyHelloCmdMUS(v SayFancyHelloCmd, w muss.Writer) (n int, err error) {
	return ord.MarshalString(v.str, nil, w)
}

func UnmarshalSayFancyHelloCmdMUS(r muss.Reader) (v SayFancyHelloCmd, n int, err error) {
	v.str, n, err = ord.UnmarshalString(nil, r)
	return
}

func SizeSayFancyHelloCmdMUS(v SayFancyHelloCmd) (size int) {
	return ord.SizeString(v.str, nil)
}

func SkipSayFancyHelloCmdMUS(r muss.Reader) (n int, err error) {
	return ord.SkipString(nil, r)
}

var SayFancyHelloCmdDTS = dts.New[SayFancyHelloCmd](SayFancyHelloCmdDTM,
	muss.MarshallerFn[SayFancyHelloCmd](MarshalSayFancyHelloCmdMUS),
	muss.UnmarshallerFn[SayFancyHelloCmd](UnmarshalSayFancyHelloCmdMUS),
	muss.SizerFn[SayFancyHelloCmd](SizeSayFancyHelloCmdMUS),
	muss.SkipperFn(SkipSayFancyHelloCmdMUS))

func MarshalUnsupportedCmdMUS(v UnsupportedCmd, w muss.Writer) (n int, err error) {
	return ord.MarshalString(v.str, nil, w)
}

func UnmarshalUnsupportedCmdMUS(r muss.Reader) (v UnsupportedCmd, n int, err error) {
	v.str, n, err = ord.UnmarshalString(nil, r)
	return
}

func SizeUnsupportedCmdMUS(v UnsupportedCmd) (size int) {
	return ord.SizeString(v.str, nil)
}

func SkipUnsupportedCmdMUS(r muss.Reader) (n int, err error) {
	return ord.SkipString(nil, r)
}

var UnsupportedCmdDTS = dts.New[UnsupportedCmd](UnsupportedCmdDTM,
	muss.MarshallerFn[UnsupportedCmd](MarshalUnsupportedCmdMUS),
	muss.UnmarshallerFn[UnsupportedCmd](UnmarshalUnsupportedCmdMUS),
	muss.SizerFn[UnsupportedCmd](SizeUnsupportedCmdMUS),
	muss.SkipperFn(SkipUnsupportedCmdMUS))

func MarshalSayFancyHelloMultiCmdMUS(v SayFancyHelloMultiCmd, w muss.Writer) (n int, err error) {
	return ord.MarshalString(v.str, nil, w)
}

func UnmarshalSayFancyHelloMultiCmdMUS(r muss.Reader) (v SayFancyHelloMultiCmd, n int, err error) {
	v.str, n, err = ord.UnmarshalString(nil, r)
	return
}

func SizeSayFancyHelloMultiCmdMUS(v SayFancyHelloMultiCmd) (size int) {
	return ord.SizeString(v.str, nil)
}

func SkipSayFancyHelloMultiCmdMUS(r muss.Reader) (n int, err error) {
	return ord.SkipString(nil, r)
}

var SayFancyHelloMultiCmdDTS = dts.New[SayFancyHelloMultiCmd](SayFancyHelloMultiCmdDTM,
	muss.MarshallerFn[SayFancyHelloMultiCmd](MarshalSayFancyHelloMultiCmdMUS),
	muss.UnmarshallerFn[SayFancyHelloMultiCmd](UnmarshalSayFancyHelloMultiCmdMUS),
	muss.SizerFn[SayFancyHelloMultiCmd](SizeSayFancyHelloMultiCmdMUS),
	muss.SkipperFn(SkipSayFancyHelloMultiCmdMUS))

func MarshalOldSayHelloCmdMUS(v OldSayHelloCmd, w muss.Writer) (n int, err error) {
	return ord.MarshalString(v.str, nil, w)
}

func UnmarshalOldSayHelloCmdMUS(r muss.Reader) (v OldSayHelloCmd, n int, err error) {
	v.str, n, err = ord.UnmarshalString(nil, r)
	return
}

func SizeOldSayHelloCmdMUS(v OldSayHelloCmd) (size int) {
	return ord.SizeString(v.str, nil)
}

func SkipOldSayHelloCmdMUS(r muss.Reader) (n int, err error) {
	return ord.SkipString(nil, r)
}

var OldSayHelloCmdDTS = dts.New[OldSayHelloCmd](OldSayHelloCmdDTM,
	muss.MarshallerFn[OldSayHelloCmd](MarshalOldSayHelloCmdMUS),
	muss.UnmarshallerFn[OldSayHelloCmd](UnmarshalOldSayHelloCmdMUS),
	muss.SizerFn[OldSayHelloCmd](SizeOldSayHelloCmdMUS),
	muss.SkipperFn(SkipOldSayHelloCmdMUS))

func MarshalResultMUS(v Result, w muss.Writer) (n int, err error) {
	n, err = ord.MarshalString(v.str, nil, w)
	if err != nil {
		return
	}
	var n1 int
	n1, err = ord.MarshalBool(v.lastOne, w)
	n += n1
	return
}

func UnmarshalResultMUS(r muss.Reader) (v Result, n int, err error) {
	v.str, n, err = ord.UnmarshalString(nil, r)
	if err != nil {
		return
	}
	var n1 int
	v.lastOne, n1, err = ord.UnmarshalBool(r)
	n += n1
	return
}

func SizeResultMUS(v Result) (size int) {
	size = ord.SizeString(v.str, nil)
	return size + ord.SizeBool(v.lastOne)
}

func SkipResultMUS(r muss.Reader) (n int, err error) {
	n, err = ord.SkipString(nil, r)
	if err != nil {
		return
	}
	var n1 int
	n1, err = ord.SkipBool(r)
	n += n1
	return
}

var ResultDTS = dts.New[Result](ResultDTM,
	muss.MarshallerFn[Result](MarshalResultMUS),
	muss.UnmarshallerFn[Result](UnmarshalResultMUS),
	muss.SizerFn[Result](SizeResultMUS),
	muss.SkipperFn(SkipResultMUS))
