// Code generated by musgen-go. DO NOT EDIT.

package versioning

import (
	dts "github.com/mus-format/mus-stream-dts-go"
	muss "github.com/mus-format/mus-stream-go"
	"github.com/mus-format/mus-stream-go/ord"
)

var OldSayHelloCmdMUS = oldSayHelloCmdMUS{}

type oldSayHelloCmdMUS struct{}

func (s oldSayHelloCmdMUS) Marshal(v OldSayHelloCmd, w muss.Writer) (n int, err error) {
	return ord.String.Marshal(v.str, w)
}

func (s oldSayHelloCmdMUS) Unmarshal(r muss.Reader) (v OldSayHelloCmd, n int, err error) {
	v.str, n, err = ord.String.Unmarshal(r)
	return
}

func (s oldSayHelloCmdMUS) Size(v OldSayHelloCmd) (size int) {
	return ord.String.Size(v.str)
}

func (s oldSayHelloCmdMUS) Skip(r muss.Reader) (n int, err error) {
	n, err = ord.String.Skip(r)
	return
}

var OldSayHelloCmdDTS = dts.New[OldSayHelloCmd](OldSayHelloCmdDTM, OldSayHelloCmdMUS)
