// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: hello-world_protobuf/data.proto

package hwp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str string `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *SayHelloData) Reset() {
	*x = SayHelloData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hello_world_protobuf_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayHelloData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloData) ProtoMessage() {}

func (x *SayHelloData) ProtoReflect() protoreflect.Message {
	mi := &file_hello_world_protobuf_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloData.ProtoReflect.Descriptor instead.
func (*SayHelloData) Descriptor() ([]byte, []int) {
	return file_hello_world_protobuf_data_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloData) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type SayFancyHelloData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str string `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *SayFancyHelloData) Reset() {
	*x = SayFancyHelloData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hello_world_protobuf_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayFancyHelloData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayFancyHelloData) ProtoMessage() {}

func (x *SayFancyHelloData) ProtoReflect() protoreflect.Message {
	mi := &file_hello_world_protobuf_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayFancyHelloData.ProtoReflect.Descriptor instead.
func (*SayFancyHelloData) Descriptor() ([]byte, []int) {
	return file_hello_world_protobuf_data_proto_rawDescGZIP(), []int{1}
}

func (x *SayFancyHelloData) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type GreetingData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str string `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *GreetingData) Reset() {
	*x = GreetingData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hello_world_protobuf_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetingData) ProtoMessage() {}

func (x *GreetingData) ProtoReflect() protoreflect.Message {
	mi := &file_hello_world_protobuf_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetingData.ProtoReflect.Descriptor instead.
func (*GreetingData) Descriptor() ([]byte, []int) {
	return file_hello_world_protobuf_data_proto_rawDescGZIP(), []int{2}
}

func (x *GreetingData) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

var File_hello_world_protobuf_data_proto protoreflect.FileDescriptor

var file_hello_world_protobuf_data_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2d, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x20, 0x0a, 0x0c, 0x53,
	0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x22, 0x25, 0x0a,
	0x11, 0x53, 0x61, 0x79, 0x46, 0x61, 0x6e, 0x63, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x73, 0x74, 0x72, 0x22, 0x20, 0x0a, 0x0c, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x42, 0x47, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6d, 0x64, 0x2d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f,
	0x63, 0x6d, 0x64, 0x2d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x2d, 0x67, 0x6f, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2d, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x68, 0x77, 0x70, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hello_world_protobuf_data_proto_rawDescOnce sync.Once
	file_hello_world_protobuf_data_proto_rawDescData = file_hello_world_protobuf_data_proto_rawDesc
)

func file_hello_world_protobuf_data_proto_rawDescGZIP() []byte {
	file_hello_world_protobuf_data_proto_rawDescOnce.Do(func() {
		file_hello_world_protobuf_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_hello_world_protobuf_data_proto_rawDescData)
	})
	return file_hello_world_protobuf_data_proto_rawDescData
}

var file_hello_world_protobuf_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hello_world_protobuf_data_proto_goTypes = []any{
	(*SayHelloData)(nil),      // 0: protobuf.SayHelloData
	(*SayFancyHelloData)(nil), // 1: protobuf.SayFancyHelloData
	(*GreetingData)(nil),      // 2: protobuf.GreetingData
}
var file_hello_world_protobuf_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hello_world_protobuf_data_proto_init() }
func file_hello_world_protobuf_data_proto_init() {
	if File_hello_world_protobuf_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hello_world_protobuf_data_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SayHelloData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hello_world_protobuf_data_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SayFancyHelloData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hello_world_protobuf_data_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GreetingData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hello_world_protobuf_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hello_world_protobuf_data_proto_goTypes,
		DependencyIndexes: file_hello_world_protobuf_data_proto_depIdxs,
		MessageInfos:      file_hello_world_protobuf_data_proto_msgTypes,
	}.Build()
	File_hello_world_protobuf_data_proto = out.File
	file_hello_world_protobuf_data_proto_rawDesc = nil
	file_hello_world_protobuf_data_proto_goTypes = nil
	file_hello_world_protobuf_data_proto_depIdxs = nil
}
